config/routes.rb
Rails.application.routes.draw do
  root to: 'home#Index'

  post "/date_part" => "type_locations#date_part", :as => :typelocation_date_part
  post "/date_part_2" => "type_locations#date_part_2", :as => :typelocation_date_part_2


  get 'adminis/user_list', to: 'adminis#user_list', as: 'user_list'
  get 'adminis/reservation', to: 'adminis#reservation', as: 'reservation'
  get 'adminis/location', to: 'adminis#location', as: 'location'
  get 'adminis/location/new', to: 'adminis#new_location', as: 'new_location'
  post 'adminis/location/new', to: 'adminis#create_location', as: 'create_location'


  get 'adminis/category', to: 'adminis#category', as: 'category'
  get 'adminis/camping', to: 'adminis#camping', as: 'campinge'
  get 'adminis/camping/new', to: 'adminis#new_camping', as: 'new_camping'

  post 'adminis/camping/new', to: 'adminis#create_camping', as: 'create_camping'

  # Resource without 's' to not use id of camping in the url
  resource :camping, only:[:show,:edit, :update], path: 'admin/camping'
  resources :type_locations
  resources :reservations


  devise_for :admins, path: 'admins'
  devise_for :clients, path: 'clients'

  resources :adminis do
    member do
      get 'user_list'
      get 'reservation'
      get 'location'
      get 'category'
      get 'camping'
    end

end
end

app/models/type_location.rb
class TypeLocation < ApplicationRecord
  belongs_to :category, optional: true
  has_many :locations
  validates :title, :price_per_night, :nb_person, presence: true
end

app/controllers/type_locations_controller.rb
require 'json'

class TypeLocationsController < ApplicationController
  before_action :set_type_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  # GET /type_locations
  # GET /type_locations.json
  def index
    @type_locations = TypeLocation.all
  end

  # GET /type_locations/1
  # GET /type_locations/1.json
  def show
    @@type_location = @type_location
  end

  def date_part
    @reception_begin = params[:data_infos];
    puts @reception_begin 
  end

  def date_part_2
    # Data from params
    puts params
    tl = TypeLocation.find_by_id(params.permit(:id_type_location).values.first)
    proposition_end = Date.parse(params.permit(:date_end).values.first)
    proposition_begin = Date.parse(params.permit(:date_begin).values.first)
    
    # useful var
    id_first_free_loc = nil
    
    tl.locations.each do |l|
      free_loc = true
      l.reservations.each do |reserv| 
        if ( ( (reserv.date_begin >= proposition_begin) && (reserv.date_begin < proposition_end) ) || ( (reserv.date_end > proposition_begin) && (reserv.date_end <= proposition_end) || (( reserv.date_begin < proposition_begin) && (reserv.date_end) > proposition_end ) )) 
          puts "Dans le if"
          # Une réservation est dans le créneau choisie, cette location n'est pas disponible
          free_loc = false
        end
      end
      puts "Fin des reservation"
      puts free_loc
      if free_loc
        # After all each of resservation, the location is free. We keep the first if of free locations
        id_first_free_loc ||= l.id
        redirect_to new_reservation_path(date_begin: params.permit(:date_begin).values.first, date_end: params.permit(:date_end).values.first, location_id: id_first_free_loc)
      end
    end

    if id_first_free_loc == nil  
      puts "Normalement, il y a alert"
      flash.now[:alert] = "Les dates ne sont pas disponibles"
    end
  end

  # GET /type_locations/new
  def new
    @type_location = TypeLocation.new
  end

  # GET /type_locations/1/edit
  def edit
  end

  # POST /type_locations
  # POST /type_locations.json
  def create
    @type_location = TypeLocation.new(type_location_params)

    update_locations_association
    update_category_association

    respond_to do |format|
      if @type_location.save
        format.html { redirect_to @type_location, notice: 'Type location was successfully created.' }
        format.json { render :show, status: :created, location: @type_location }
      else
        format.html { render :new }
        format.json { render json: @type_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_locations/1
  # PATCH/PUT /type_locations/1.json
  def update
    update_locations_association
    update_category_association
    respond_to do |format|
      if @type_location.update(type_location_params)
        format.html { redirect_to @type_location, notice: 'Type location was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_location }
      else
        format.html { render :edit }
        format.json { render json: @type_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_locations/1
  # DELETE /type_locations/1.json
  def destroy
    @type_location.destroy
    respond_to do |format|
      format.html { redirect_to type_locations_url, notice: 'Type location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_location
      @type_location = TypeLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_location_params
      hash_params = params.fetch(:type_location, {})
      if params.has_key?(:category)
        hash_params.merge(params.permit(:category))
        hash_params.permit :title, :description, :nb_person, :price_per_night, :category
      end
    end

    def update_locations_association 
      nb_form = params.require(:type_location).permit(:nb_emplacement).values.first.to_i
      nb_object = @type_location.locations.size
      if (nb_form > nb_object)
        (nb_form-nb_object).times do |i|
          @type_location.locations.push( Location.create(id_in_camping: (type_location_params[:title] + "_" + (i+1).to_s) ) )
        end
      elsif (nb_form == nb_object)
      else 
        (nb_object-nb_form).times do |i|
          @type_location.locations.last.delete
        end
      end
    end

    def update_category_association
      categ = Category.find_by_id(params.permit(:category).values.first.to_i)
      @type_location.category = categ if @type_location.category != categ
    end

end

app/helpers/type_locations_helper.rb
module TypeLocationsHelper
	def category_list_select_tag(options = {})
      select_options = Category.all.map do |c|
                     [ c.name, c.id ]
      end
      return select_options
    end
end

app/views/type_locations/_form.html.erb
<%= form_with(model: type_location, local: true) do |form| %>
  <% if type_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_location.errors.count, "error") %> prohibited this type_location from being saved:</h2>

      <ul>
      <% type_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row justify-content-center">
    <div class="col-6">
         
  <div class="form-group">
    <%= form.label :title, "Titre" %> <br/>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :category, "Catégorie"%> <br/>
    <% if cate = @type_location.category %>
      <%= select_tag :category, options_for_select(category_list_select_tag(), cate.id) %>
    <% else %>
      <%= select_tag :category, options_for_select(category_list_select_tag()) %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :description, "Description" %> <br/>
    <%= form.text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :nb_person, "Nombre de personnes" %> <br/>
    <%= form.number_field :nb_person, min:0 %>
  </div>

  <div class="form-group">
    <%= form.label :nb_emplacement, "Nombre d'emplacement de ce type" %> <br/>
    <%= form.number_field :nb_emplacement, min:0, :value => @type_location.locations.size %>
  </div>

  <div class="form-group">
    <%= form.label :price_per_night, "Prix par nuit" %> <br/>
    <%= form.number_field :price_per_night, min:0 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
</div>
<% end %>

app/views/type_locations/edit.html.erb
<div class="section-title section-title--style-1 text-center">
    <h3 class="section-title-inner heading-2 strong-400">
        <span>Modifier le type de location</span>
    </h3>
</div>

<%= render 'form', type_location: @type_location %>

<%= link_to 'Show', @type_location %> |
<%= link_to 'Back', type_locations_path %>

app/views/type_locations/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Type Locations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <tr>
      <th>Titre</th><th>Nombre de personnes</th> <% if admin_signed_in? %><th>Action (visible pour les admins uniquement)</th><% end %>
    </tr>
    <% @type_locations.each do |type_location| %>
      <tr>
        <td><%= link_to type_location.title, type_location %></td>
        <td><%= type_location.nb_person %></td>
        <% if admin_signed_in? %> <td><%= link_to 'Edit', edit_type_location_path(type_location) %> | 
        <%= link_to 'Destroy', type_location, method: :delete, data: { confirm: 'Are you sure?' } %> <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Location', new_type_location_path if admin_signed_in? %>
</div>

app/views/type_locations/new.html.erb
<div class="section-title section-title--style-1 text-center">
    <h3 class="section-title-inner heading-2 strong-400">
        <span>Créer un type de location</span>
    </h3>
</div>

<%= render 'form', type_location: @type_location %>

<%= link_to 'Back', type_locations_path %>

app/views/type_locations/show.html.erb
<p id="notice"><%= notice %></p>
<!-- Image -->
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
    <!-- IMAGE TODO --> 
    <% # = image_tag @room.cover_photo(nil), width: "100%" %> 
    Titre : <%= @type_location.title %> <hr/>
    Description : 
    <%= @type_location.description %> <hr/>
    Prix par nuit : <%= @type_location.price_per_night %> <hr/>
    Nombre de personnes : <%= @type_location.nb_person %> <hr/>
    <% if @type_location.category %> 
        Catégorie : <%= @type_location.category.name %> 
        <hr/>
    <% end %>
    <div class="container">
        <div class="section-title section-title--style-1 text-center">
            <h3 class="section-title-inner heading-2 strong-400">
                <span>Réservation :</span>
            </h3>
        </div>
        <div class="d-flex justify-content-around">
            <div> 
                Date de début: 
                <div id="datepicker_begin"></div>
            </div>
            <div> 
                Date de fin: 
                <div id="datepicker_end"></div>
            </div>
        </div>
        <!-- <div class="row justify-content-md-center">
            <button type="button" class="btn btn-styled btn-primary" id="reserv_button" disabled="true">Réserver</button>
        </div> -->
    </div>

  </div>
</div>
<br/>

<% if admin_signed_in? %>  
    <%= link_to 'Edit', edit_type_location_path(@type_location) %> |
<% end %> 
<%= link_to 'Back', type_locations_path %>
</div>
<script>
    $("#datepicker_begin").datepicker({
        minDate: 0,
        dateFormat: 'dd-mm-yy',
        onSelect: function() { 
            var dateObject = $(this).datepicker('getDate'); 
            // alert('date' + dateObject);
            $.ajax({
              url : "/date_part",
              type : "post",
              beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
              data : { data_infos: JSON.stringify(dateObject) }
            });
            $( "#datepicker_end" ).datepicker( "option", "minDate", dateObject );
            $( "#datepicker_end" ).datepicker( "option", "disabled", false );
        }
    });

    $("#datepicker_end").datepicker({
        minDate: 1,
        dateFormat: 'dd-mm-yy',
        disabled: "true",
        onSelect: function() { 
            var dateObject = $(this).datepicker('getDate'); 
            var dateObject_begin = $("#datepicker_begin").datepicker('getDate')
            $.ajax({
              url : "/date_part_2",
              type : "post",
              beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
              data : { date_end: JSON.stringify(dateObject), id_type_location: <%= @type_location.id %>, date_begin: JSON.stringify(dateObject_begin) }
            });
        }

    });
</script>