config/routes.rb
Rails.application.routes.draw do
  root to: 'home#Index'

  post "/date_part" => "type_locations#date_part", :as => :typelocation_date_part
  post "/date_part_2" => "type_locations#date_part_2", :as => :typelocation_date_part_2


  get 'adminis/user_list', to: 'adminis#user_list', as: 'user_list'
  get 'adminis/reservation', to: 'adminis#reservation', as: 'reservation'
  get 'adminis/location', to: 'adminis#location', as: 'location'
  get 'adminis/location/new', to: 'adminis#new_location', as: 'new_location'
  post 'adminis/location/new', to: 'adminis#create_location', as: 'create_location'


  get 'adminis/category', to: 'adminis#category', as: 'category'
  get 'adminis/camping', to: 'adminis#camping', as: 'campinge'
  get 'adminis/camping/new', to: 'adminis#new_camping', as: 'new_camping'

  post 'adminis/camping/new', to: 'adminis#create_camping', as: 'create_camping'

  # Resource without 's' to not use id of camping in the url
  resource :camping, only:[:show,:edit, :update], path: 'admin/camping'
  resources :type_locations
  resources :reservations


  devise_for :admins, path: 'admins'
  devise_for :clients, path: 'clients'

  resources :adminis do
    member do
      get 'user_list'
      get 'reservation'
      get 'location'
      get 'category'
      get 'camping'
    end

end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :location
	belongs_to :client

	# Validate when title, price, nb_person and location are present
   	validates :date_begin, :date_end, :price, :client, :location, presence: true

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]
  before_action :authenticate_client!, only: [:create, :new]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = current_client.reservations.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new(reservation_params)
    @reservation.client = current_client
    @reservation.location = Location.find_by_id(params.permit(:location_id).values.first.to_i)

    # Price_per_night of location is prioritized 
    @price_p_n = @reservation.location.price_per_night || @reservation.location.type_location.price_per_night
    
    @reservation.date_begin = Date.parse(params.permit(:date_begin).values.first)+1
    @reservation.date_end = Date.parse(params.permit(:date_end).values.first)+1

    @reservation.price = (@reservation.date_end - @reservation.date_begin) * @price_p_n
    @reservation.save
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    r = Reservation.last
    # r.completed = true
    # r.save
    redirect_to reservations_path(r)
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.fetch(:reservation, {})
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
	def amount_for_stripe(price_total)
		# Stripe requires the amount in centimes
		return price_total * 100
	end
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= form_tag charges_path do %>
					<article>
				    	<% if flash[:error].present? %>
				      		<div id="error_explanation">
				        		<p><%= flash[:error] %></p>
				      		</div>
				    	<% end %>
				    	<label class="amount">
				    		<span>Payer</span>
				    	</label>
				  	</article>
					
					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
				        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
				        data-name="Réservation camping"
				        data-description="Reservation at <%= Camping.first.name %>"
				        data-amount="<%= amount_for_stripe(@total_price) %>"
				        data-locale="auto"
				        data-currency="eur"
				        data-zip-code="true">
				    </script>
				<% end %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nom de l'emplacement </th>
      <th> Date de début de la réservation </th>
      <th> Date de fin de la réservation </th>
      <th> Date de création de la réservation </th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.location.type_location.title %> </td>
        <td><%= reservation.date_begin %> </td>
        <td><%= reservation.date_end %> </td>
        <td><%= reservation.created_at %> </td>        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reservations/new.html.erb
<div class="container">
<div class="section-title section-title--style-1 text-center">
    <h3 class="section-title-inner heading-2 strong-400">
        <span>Réservation</span>
    </h3>
</div>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-6">
  	<div class="row">
  		<div class="card--hover">
    		<div class="card-body">
        		<h4 class="card-title"><%= @reservation.location.type_location.title %></h4>
        		<div class="row align-items-center">
        			<div class="col">
        				<span class="card-text">Date de début : <%= @reservation.date_begin %></span>
        			</div>
        			<div class="col text-right">
        				<span class="card-text">Date de fin : <%= @reservation.date_end %></span>
        			</div>
        		</div>
        	</div>
        </div>
    </div>
  </div>
  	
  <!-- RIGHT PANEL -->
	  <div class="col-md-6">
  <div class="pricing-plans pricing-plans--style-1">
	<div class="row cols-xs-space cols-sm-space cols-md-space">
	    <div class="block block-pricing">
	        <div class="block-body">
	            <h2 class="plan-title heading-4 text-center strong-600">Prix</h2>
	            <h3 class="price-tag strong-600">
	                <%= @reservation.price %><sup>€</sup>
	            </h3>
	            
	            <%= form_tag reservations_path do %>
					<article>
				    	<% if flash[:error].present? %>
				      		<div id="error_explanation">
				        		<p><%= flash[:error] %></p>
				      		</div>
				    	<% end %>
				  	</article>
					
					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
				        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
				        data-name="Réservation camping"
				        data-description="Reservation dans l'établissement <%= Camping.first.name %>"
				        data-amount="<%= amount_for_stripe(@reservation.price) %>"
				        data-locale="fr"
		                data-currency="eur"
                		data-zip-code="true"
                		data-label="Régler la somme"
                		data-billing-address="true">
				    </script>
				<% end %>
	        </div>
	    </div>
	  </div>
	</div>
  </div>
</div>


<%= link_to 'Back', type_locations_path(@type_location) %>
</div>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>