config/routes.rb
Rails.application.routes.draw do
  root to: 'home#Index'

  post "/date_part" => "type_locations#date_part", :as => :typelocation_date_part
  post "/date_part_2" => "type_locations#date_part_2", :as => :typelocation_date_part_2


  get 'adminis/user_list', to: 'adminis#user_list', as: 'user_list'
  get 'adminis/reservation', to: 'adminis#reservation', as: 'reservation'
  get 'adminis/location', to: 'adminis#location', as: 'location'
  get 'adminis/location/new', to: 'adminis#new_location', as: 'new_location'
  post 'adminis/location/new', to: 'adminis#create_location', as: 'create_location'


  get 'adminis/category', to: 'adminis#category', as: 'category'
  get 'adminis/camping', to: 'adminis#camping', as: 'campinge'
  get 'adminis/camping/new', to: 'adminis#new_camping', as: 'new_camping'

  post 'adminis/camping/new', to: 'adminis#create_camping', as: 'create_camping'

  # Resource without 's' to not use id of camping in the url
  resource :camping, only:[:show,:edit, :update], path: 'admin/camping'
  resources :type_locations
  resources :reservations


  devise_for :admins, path: 'admins'
  devise_for :clients, path: 'clients'

  resources :adminis do
    member do
      get 'user_list'
      get 'reservation'
      get 'location'
      get 'category'
      get 'camping'
    end

end
end

app/controllers/adminis_controller.rb
class AdminisController < ApplicationController
before_action :authenticate_admin!

def home
end

	def user_list
	    @user_list = Client.all
	end


  def destroy
    @user_list = Client.find_by(params[:id])
    @user_list.destroy
    redirect_to user_list_path
    respond_to do |format|
      format.html { redirect_to user_list_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reservation
    @reservation = Reservation.all
  end

  def location
    @location = Location.all
  end

  def new_location
    @location = Location.new
  end
def create_camping
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully added.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  def camping
    @camping = Camping.all
  end

  def new_camping
    @camping = Camping.new
  end
def create_camping
    @camping = Camping.new(camping_params)

    respond_to do |format|
      if @camping.save
        format.html { redirect_to @camping, notice: 'Camping was successfully added.' }
        format.json { render :show, status: :created, location: @camping }
      else
        format.html { render :new }
        format.json { render json: @camping.errors, status: :unprocessable_entity }
      end
    end
  end

  def category
    @category = Category.all
  end

  private

  def camping_params
    params.require(:camping).permit(:name, :description, :number, :adress)
  end

  def location_params
    params.require(:location).permit(:price_per_night)
  end

end

app/views/adminis/camping.html.erb
<section class="slice-sm sct-color-1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.w3-btn {margin-bottom:5px;}
</style>
<div class="col-lg-8">
    <div class="main-content">
        <!-- Page title -->
        <div class="page-title">
            <div class="row align-items-center">
                <div class="col-lg-6 col-12">
                    <h2 class="heading heading-5 text-capitalize strong-500 mb-0">
                        <a href="#" class="link text-underline--none">
                            <i class="ion-ios-arrow-back"></i> Location
                        </a>
                    </h2>
                </div>
                <div class="col-lg-6 col-12">

                </div>
            </div>
        </div>

        <div class="link-menu link-menu--style-3 py-4 border-bottom">
            <a class<%= link_to 'Clients', user_list_path %></a></a>
            <a class<%= link_to 'Reservations', reservation_path %></a></a>
            <a class<%= link_to 'Locations', user_list_path %></a></a>
            <a class<%= link_to 'Categories', category_path %></a></a>
            <a href="../../pages/profile/account-security.html"class="active">Campings</a>
        </div>

        <button class="w3-btn w3-white w3-border w3-border-blue w3-round-large">Ajouter un camping</button>

        <!-- Order history table -->
        <div class="card no-border">
            <div>
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nom</th>
                            <th>Description</th>
                            <th>Numéro</th>
                            <th>Adresse</th>
                            <th>Ajouté le:</th>

                        </tr>
                    </thead>

                    <tbody>

                        <% @camping.each do |campings| %>
                        <tr>
                            <td>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= campings.id %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= campings.name %></span>
                            </td>

                            <td class="product-name">
                                <span class="pr-4"><%= campings.description %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= campings.number %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= campings.adress %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= campings.created_at %></span>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <a class<%= link_to 'Modifier', edit_camping_path %></a></a>
            </div>
        </div>

    </div>
</div>
</div>
</section>

app/views/adminis/category.html.erb
<section class="slice-sm sct-color-1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.w3-btn {margin-bottom:5px;}
</style>
<div class="col-lg-8">
    <div class="main-content">
        <!-- Page title -->
        <div class="page-title">
            <div class="row align-items-center">
                <div class="col-lg-6 col-12">
                    <h2 class="heading heading-5 text-capitalize strong-500 mb-0">
                        <a href="#" class="link text-underline--none">
                            <i class="ion-ios-arrow-back"></i> Clients
                        </a>
                    </h2>
                </div>
                <div class="col-lg-6 col-12">

                </div>
            </div>
        </div>

        <div class="link-menu link-menu--style-3 py-4 border-bottom">
            <a class<%= link_to 'Clients', user_list_path %></a></a>
            <a class<%= link_to 'Reservations', reservation_path %></a></a>
            <a class<%= link_to 'Locations', location_path %></a></a>
            <a href="../../pages/profile/account-settings.html" class="active">Categories</a>
            <a class<%= link_to 'Campings', campinge_path %></a></a>
        </div>

        <button class="w3-btn w3-white w3-border w3-border-blue w3-round-large">Ajouter une category</button>


        <!-- Order history table -->
        <div class="card no-border">
            <div>
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </th>
                            <th>Id</th>
                            <th>Nom</th>
                            <th>Description</th>
                            <th>crée le:</th>

                        </tr>
                    </thead>

                    <tbody>

                        <% @category.each do |categories| %>
                        <tr>
                            <td>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= categories.id %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= categories.name %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= categories.description %></span>
                            </td>

                            <td class="product-name">
                                <span class="pr-4"><%= categories.created_at %></span>
                            </td>


                        </tr>
                        <% end %>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
</div>
</section>

app/views/adminis/location.html.erb
<section class="slice-sm sct-color-1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.w3-btn {margin-bottom:5px;}
</style>
<div class="col-lg-8">
    <div class="main-content">
        <!-- Page title -->
        <div class="page-title">
            <div class="row align-items-center">
                <div class="col-lg-6 col-12">
                    <h2 class="heading heading-5 text-capitalize strong-500 mb-0">
                        <a href="#" class="link text-underline--none">
                            <i class="ion-ios-arrow-back"></i> Location
                        </a>
                    </h2>
                </div>
                <div class="col-lg-6 col-12">

                </div>
            </div>
        </div>

        <div class="link-menu link-menu--style-3 py-4 border-bottom">
            <a class<%= link_to 'Clients', user_list_path %></a></a>
            <a class<%= link_to 'Reservations', reservation_path %></a></a>
            <a href="../../pages/profile/account-cards.html" class="active">Locations</a>
            <a class<%= link_to 'Categories', category_path %></a></a>
            <a class<%= link_to 'Campings', campinge_path %></a></a>
        </div>

        <button class="w3-btn w3-white w3-border w3-border-blue w3-round-large">Ajouter une Location</button>


        <!-- Order history table -->
        <div class="card no-border">
            <div>
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </th>
                            <th>Id</th>
                            <th>Prix par nuit</th>
                            <th>Crée le:</th>

                        </tr>
                    </thead>

                    <tbody>

                        <% @location.each do |locations| %>
                        <tr>
                            <td>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= locations.id %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= locations.price_per_night %></span>
                            </td>

                            <td class="product-name">
                                <span class="pr-4"><%= locations.created_at %></span>
                            </td>

                        </tr>
                        <% end %>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
</div>
</section>

app/views/adminis/new_camping.html.erb
<section class="slice-lg has-bg-cover bg-size-cover" style="background-image: url(../../assets/images/backgrounds/slider/img-52.jpg); background-position: bottom center;">
    <div class="container">
        <div class="row justify-content-center cols-xs-space">
            <div class="col-lg-6">
                <div class="form-card form-card--style-2 z-depth-2-top">
                    <div class="form-header text-center">
                        <div class="form-header-icon">
                            <i class="icon ion-log-in"></i>
                        </div>
                    </div>

                    <div class="form-body">

                        <div class="text-center px-2">
                            <h4 class="heading heading-4 strong-400 mb-4">Ajouter un camping</h4>
                        </div>


                        <%= form_for @camping do |f| %>
                          <% if @camping.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(event.errors.count, "error") %> prohibited this camping from being saved:</h2>

                              <ul>
                              <% event.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>
                            <div class="row">

                                <div class="col-md">
                                    <div class="form-group">
                                        <%= f.label :name, "Nom" %>
                                        <%= f.text_field :name, class: 'form-control form-control-lg' %>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md">
                                    <div class="form-group">
                                        <%= f.label :description, "Description" %>
                                        <%= f.text_field :description, class: 'form-control form-control-lg' %>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md">
                                    <div class="form-group">
                                        <%= f.label :number, "Téléphone" %>
                                        <%= f.number_field :number, class: 'form-control form-control-lg' %>
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md">
                                    <div class="form-group">
                                        <%= f.label :adress, "Adresse" %>
                                        <%= f.text_field :adress, class: 'form-control form-control-lg' %>
                                    </div>
                                </div>
                            </div>


                            <div class="actions">
                            <%= f.submit "Ajouté", class: 'btn btn-styled  btn-base-1 mt-4' %>

                          </div>
                            <% end %>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/adminis/new_location.html.erb
<section class="slice-lg has-bg-cover bg-size-cover" style="background-image: url(../../assets/images/backgrounds/slider/img-52.jpg); background-position: bottom center;">
    <div class="container">
        <div class="row justify-content-center cols-xs-space">
            <div class="col-lg-6">
                <div class="form-card form-card--style-2 z-depth-2-top">
                    <div class="form-header text-center">
                        <div class="form-header-icon">
                            <i class="icon ion-log-in"></i>
                        </div>
                    </div>

                    <div class="form-body">

                        <div class="text-center px-2">
                            <h4 class="heading heading-4 strong-400 mb-4">Ajouter un camping</h4>
                        </div>


                        <%= form_for @location do |f| %>
                          <% if @location.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(event.errors.count, "error") %> prohibited this camping from being saved:</h2>

                              <ul>
                              <% event.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>
                            <div class="row">

                                <div class="col-md">
                                    <div class="form-group">
                                        <%= f.label :price_per_night, "Nom" %>
                                        <%= f.number_field :price_per_night, class: 'form-control form-control-lg' %>
                                    </div>
                                </div>
                            </div>


                            <% end %>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/adminis/reservation.html.erb
<section class="slice-sm sct-color-1">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<style>
.w3-btn {margin-bottom:5px;}
</style>
<div class="col-lg-8">
    <div class="main-content">
        <!-- Page title -->
        <div class="page-title">
            <div class="row align-items-center">
                <div class="col-lg-6 col-12">
                    <h2 class="heading heading-5 text-capitalize strong-500 mb-0">
                        <a href="#" class="link text-underline--none">
                            <i class="ion-ios-arrow-back"></i> Clients
                        </a>
                    </h2>
                </div>
                <div class="col-lg-6 col-12">

                </div>
            </div>
        </div>

        <div class="link-menu link-menu--style-3 py-4 border-bottom">
            <a class<%= link_to 'Clients', user_list_path %></a>
            <a href="../../pages/profile/account-orders.html" class="active">Reservations</a>
            <a class<%= link_to 'Locations', location_path %></a></a>
            <a class<%= link_to 'Categories', category_path %></a></a>
            <a class<%= link_to 'Campings', campinge_path %></a></a>
        </div>

        <button class="w3-btn w3-white w3-border w3-border-blue w3-round-large">Ajouter une reservation</button>


        <!-- Order history table -->
        <div class="card no-border">
            <div>
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </th>
                            <th>Id</th>
                            <th>date arrivé</th>
                            <th>date depart</th>
                            <th>Prix</th>
                            <th>Nom</th>
                            <th>Prenom</th>
                        </tr>
                    </thead>

                    <tbody>

                        <% @reservation.each do |reservations| %>
                        <tr>
                            <td>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= reservations.id %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= reservations.date_begin %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= reservations.date_end %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= reservations.price %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= reservations.client.name %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= reservations.client.firstname %></span>
                            </td>


                        </tr>
                        <% end %>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
</div>
</section>

app/views/adminis/user_list.html.erb
<section class="slice-sm sct-color-1">
<div class="col-lg-8">
    <div class="main-content">
        <!-- Page title -->
        <div class="page-title">
            <div class="row align-items-center">
                <div class="col-lg-6 col-12">
                    <h2 class="heading heading-5 text-capitalize strong-500 mb-0">
                        <a href="#" class="link text-underline--none">
                            <i class="ion-ios-arrow-back"></i> Clients
                        </a>
                    </h2>
                </div>
                <div class="col-lg-6 col-12">

                </div>
            </div>
        </div>

        <div class="link-menu link-menu--style-3 py-4 border-bottom">
            <a href="../../pages/profile/account-settings.html" class="active">Clients</a>
            <a class<%= link_to 'Reservations', reservation_path %></a></a>
            <a class<%= link_to 'Locations', location_path %></a></a>
            <a class<%= link_to 'Categories', category_path %></a></a>
            <a class<%= link_to 'Campings', campinge_path %></a></a>
        </div>

        <!-- Order history table -->
        <div class="card no-border">
            <div>
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </th>
                            <th>Id</th>
                            <th>Nom</th>
                            <th>Prenom</th>
                            <th>email</th>
                            <th>inscrit le:</th>
                            <th>Derniere connection</th>
                        </tr>
                    </thead>

                    <tbody>

                        <% @user_list.each do |client| %>
                        <tr>
                            <td>
                                <div class="checkbox">
                                    <input type="checkbox" name="checkbox_example_1">
                                    <label></label>
                                </div>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= client.id %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= client.name %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= client.firstname %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= client.email %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= client.created_at %></span>
                            </td>
                            <td class="product-name">
                                <span class="pr-4"><%= client.last_sign_in_at %></span>
                            </td>




                        </tr>
                        <% end %>

                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
</div>
</section>