config/routes.rb
Rails.application.routes.draw do
  root to: 'home#Index'

  post "/date_part" => "type_locations#date_part", :as => :typelocation_date_part
  post "/date_part_2" => "type_locations#date_part_2", :as => :typelocation_date_part_2


  get 'adminis/user_list', to: 'adminis#user_list', as: 'user_list'
  get 'adminis/reservation', to: 'adminis#reservation', as: 'reservation'
  get 'adminis/location', to: 'adminis#location', as: 'location'
  get 'adminis/location/new', to: 'adminis#new_location', as: 'new_location'
  post 'adminis/location/new', to: 'adminis#create_location', as: 'create_location'


  get 'adminis/category', to: 'adminis#category', as: 'category'
  get 'adminis/camping', to: 'adminis#camping', as: 'campinge'
  get 'adminis/camping/new', to: 'adminis#new_camping', as: 'new_camping'

  post 'adminis/camping/new', to: 'adminis#create_camping', as: 'create_camping'

  # Resource without 's' to not use id of camping in the url
  resource :camping, only:[:show,:edit, :update], path: 'admin/camping'
  resources :type_locations
  resources :reservations


  devise_for :admins, path: 'admins'
  devise_for :clients, path: 'clients'

  resources :adminis do
    member do
      get 'user_list'
      get 'reservation'
      get 'location'
      get 'category'
      get 'camping'
    end

end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
                  <footer id="footer" class="footer">
  <div class="footer-top">
      <div class="container">
          <div class="row cols-xs-space cols-sm-space cols-md-space">
              <div class="col-lg-5">
                  <div class="col">
                      <%= image_tag 'logo2b.png', alt: "logo Campee", height:"30px" %>
                      <span class="clearfix"></span>
                      <span class="heading heading-sm c-gray-light strong-400">Un site. Une infinité de solutions.</span>
                      <p class="mt-3">
                          Notre équipe de développeurs est à votre service pour vos réalisations web et mobile pour votre camping de rêve.
                      </p>

                      <div class="copyright mt-4">
                          <p>
                              Copyright &copy; 2018                                <a href="#" >
                                  <strong>Campee</strong>
                              </a> -
                              All rights reserved
                          </p>
                      </div>
                  </div>
              </div>

              

              <div class="col-lg-2">
                  <div class="col">
                      <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
                          Entreprise
                      </h4>

                      <ul class="footer-links">
                           <li>
                               <a href="#" title="Home">
                                   Accueil
                               </a>
                           </li>
                           <li>
                               <a href="#" title="About us">
                           A propos de nous
                               </a>
                           </li>
                           <li>
                               <a href="#" title="Services">
                                   Nos Services
                               </a>
                           </li>
                           <li>
                               <a href="#" title="Blog">
                                   Blog
                               </a>
                           </li>
                           <li>
                               <a href="#" title="Contact">
                                   Contact
                               </a>
                           </li>
                       </ul>
                  </div>
              </div>

              <div class="col-lg-3">
                  <div class="col">
                      <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
                          Suivez-nous sur les réseaux sociaux
                      </h4>

                      <ul class="social-media social-media--style-1-v4">
                          <li>
                              <a href="#" class="facebook" target="_blank" data-toggle="tooltip" data-original-title="Facebook">
                                  <i class="fa fa-facebook"></i>
                              </a>
                          </li>
                          <li>
                              <a href="#" class="instagram" target="_blank" data-toggle="tooltip" data-original-title="Instagram">
                                  <i class="fa fa-instagram"></i>
                              </a>
                          </li>
                          <li>
                              <a href="#" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Dribbble">
                                  <i class="fa fa-dribbble"></i>
                              </a>
                          </li>
                          <li>
                              <a href="#" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Github">
                                  <i class="fa fa-github"></i>
                              </a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Brand/Logo -->
            <a class="navbar-brand" href="<%= root_path %>">

                </a>

<div class="d-inline-block">
    <!-- Navbar toggler  -->
    <button class="navbar-toggler hamburger hamburger-js hamburger--spring" type="button" data-toggle="collapse" data-target="#navbar_main" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="hamburger-box">
            <span class="hamburger-inner"></span>
        </span>
    </button>
</div>

<div class="collapse navbar-collapse align-items-center justify-content-center" id="navbar_main">
<!-- Navbar search - For small resolutions -->
<div class="navbar-search-widget b-xs-bottom py-3 d-lg-none d-none">
<form class="" role="form">
<div class="input-group input-group-lg">
    <input type="text" class="form-control" placeholder="Search for...">
    <span class="input-group-btn">
    <button class="btn btn-base-3" type="button">Go!</button>
    </span>
</div>
</form>
</div>

<!-- Navbar links -->
<ul class="navbar-nav">

<li class="nav-item dropdown megamenu">

<li class="nav-item dropdown megamenu">
<a class="nav-link" href="<%= user_list_path %>">
Admin</a>
</li>


<% if client_signed_in? %>
  <li class="nav-item dropdown megamenu">
    <a class="nav-link"><%= "Bonjour"+" "+ current_client.firstname%></a>
  </li>
  <li class="nav-item dropdown megamenu">
     <a class="nav-link" <%= link_to "Se deconnecter", destroy_client_session_path, method: :delete %>
   </li>
   <% else %>
   <li class="nav-item dropdown megamenu">
     <a class="nav-link" href="<%= new_client_session_path %>">Se connecter</a>
   </li>
   <li cclass="nav-item dropdown megamenu">
     <a class="nav-link" href="<%= new_client_registration_path %>">S'inscrire</a>
   </li>
<% end %>

<div class="dropdown-menu">
    <div class="mega-dropdown-menu row row-no-padding">
        <div class="mega-dropdown-col mega-dropdown-col-cover mega-dropdown-col-cover--left col-lg-5 d-none d-lg-block d-xl-block" style="background-image: url(../../assets/images/prv/other/img-14-1000x900.jpg); background-position: center center;">
            <span class="mask mask-base-1--style-1 alpha-8"></span>
            <div class="mega-dropdown-col-inner d-flex align-items-center no-padding">
                <div class="col">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <div class="px-4">
                                <h2 class="heading heading-2 strong-600 c-white">
                                    Documentation and Shortcodes
                                </h2>
                                <p class="strong-300 c-white mt-4">
                                    Get started fast and easy with Boomerang using the documentation and shortcode examples. No matter
                                    you are a developer or new to web design, you will
                                    find our theme very easy to customize with
                                    an intuitive HTML markup.
                                </p>
                                <div class="btn-container mt-5">
                                    <a href="../../documentation/getting-started/introduction.html" target="_blank" class="btn btn-styled btn-white btn-outline btn-circle">Read the Docs</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-lg-2 ml-lg-auto">
            <ul class="megadropdown-links">
                <li>
                    <a class="dropdown-item" href="../../documentation/components/alerts.html">
                        Alerts
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/badges.html">
                        Badges
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/buttons.html">
                        Buttons
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/cards.html">
                        Cards
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/collapse.html">
                        Collapse
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/countdown.html">
                        Countdown
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/dropdown.html">
                        Dropdowns
                    </a>
                </li>

                <li>
                    <a class="dropdown-item" href="../../documentation/components/forms.html">
                        Forms
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/instagram.html">
                        Instagram
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/lightbox.html">
                        Lightbox
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/maps.html">
                        Maps
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/masonry.html">
                        Masonry
                    </a>
                </li>
            </ul>
        </div>

        <div class="col-md-4 col-lg-2">
            <ul class="megadropdown-links">
                <li>
                    <a class="dropdown-item" href="../../documentation/components/pagination.html">
                        Pagination
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/progress.html">
                        Progress bars
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/recaptcha.html">
                        Recaptcha
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/content/titles.html">
                        Section titles
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/forms.html#ex_component_sliders">
                        Sliders
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/tabs.html">
                        Tabs
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/components/typed-animations.html">
                        Typed animations
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/headers.html">
                        Headers
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../html/default/sliders/boomerang-slider/index.html">
                        Boomerang slider
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../html/default/sliders/revolution-slider/index.html">
                        Revolution slider
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/footers.html">
                        Footers
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/hero.html">
                        Hero blocks
                    </a>
                </li>
            </ul>
        </div>

        <div class="col-md-4 col-lg-2">
            <ul class="megadropdown-links">

                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/icon.html">
                        Icon blocks
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/jobs.html">
                        Job blocks
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/pricing.html">
                        Pricing blocks
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/product.html">
                        Product blocks
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/real-estate.html">
                        Real-Estate blocks
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/team.html">
                        Team blocks
                    </a>
                </li>
                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/testimonials.html">
                        Testimonial blocks
                    </a>
                </li>

                <li>
                    <a class="dropdown-item" href="../../documentation/blocks/comments.html">
                        Comment blocks
                      </a>
                  </li>
              </ul>
          </div>
      </div>
  </div>
</li>
</ul>

app/views/layouts/_maps.html.erb
<section class="sct-color-1">
    <!-- Map canvas -->
    <div id="google-map">
        <!-- #google-container will contain the map  -->
        <div id="map_canvas" class="map-canvas" ></div>
    </div>
</div>


<!-- Google maps -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBuyKngB9VC3zgY_uEB-DKL9BKYMekbeY&callback=initMap" type="text/javascript"></script>
<script src="../../assets/js/google-maps/google-maps-blue.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Campee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="/assets/mystyle.css" media="screen" rel="stylesheet" />

    <link href="https://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="../../assets/vendor/bootstrap/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet">
    <%= favicon_link_tag 'favicon2.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>

  <div class="container">
  </div>

  <div class="body-wrap shop-default shop-minimalist">
    <div id="st-container" class="st-container">
      <div class="st-pusher">
        <div class="st-content">
          <div class="st-content-inner">

              <!-- Header -->
            <div class="header">
              <!-- Navbar -->
                  <nav class="navbar navbar-expand-lg navbar--bold navbar--style-2 navbar-light bg-default  navbar--bb-1px">
                  <div class="container navbar-container">

                  <%= render 'layouts/header' %>

                  <div class=" d-none d-lg-inline-block d-xl-inline-block">
                  <ul class="navbar-nav ml-auto" data-hover="dropdown">
                  </ul>
                                </div>

                              </div><!-- END: container -->
                            </nav><!-- END: navbar -->
                          </div><!-- END: header -->

                          <%= yield %>
                  <%= render 'layouts/footer' %>

                </div><!-- END: st-content-inner -->
              </div><!-- END: st-content -->
            </div><!-- END: st-pusher -->
          </div><!-- END: st-container -->
        </div><!-- END: body-wrap -->


<% unless flash.empty? %>
     <script type="text/javascript">
          <% flash.each do |f| %>
	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
	     	 toastr['<%= type %>']('<%= f[1] %>');
	   <% end %>
     </script>
<% end %>


      </body>
    </html>